# https://github.com/github/pages-gem/blob/master/lib/github-pages/configuration.rb
jailed: false
future: true
#theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: paragraph_end
  syntax_highlighter_opts:
    default_lang: plaintext
exclude:
  - 'CNAME'

# https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
plugins:
  - jekyll-coffeescript
  #- jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings
