name: Refresh

on:
  workflow_dispatch:
  schedule:
    # Refresh every weekend
    - cron: '0 2 * * 6'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Refresh github projects
        env:
          GITHUB_TOKEN: ${{ secrets.ABOUT_GITHUB_TOKEN }}
        run: |
          set -ex
          make github-report
      - name: Commit, Push
        run: |
          set -ex
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet --exit-code && exit
          git commit -a -m 'Refresh github projects'
          git push
